### ISSUE TITLE
Compilation Error

### ISSUE THREAD

**Issue by kenadet** [kmkatsma/angular2-webpack-starter-gentelella#1]
There is a compilation error when I run this. It gives:
 
`Cannot find module 'assets-webpack-plugin'`

**Comment by kenadet** [comment]
I was able to bypass this when I used `yarn` but still wasn't working

**Comment by aperepjolkin** [comment]
I had the same error , try to install this "npm install assets-webpack-plugin --save-dev"

**Comment by Tonio31** [comment]
I had the same error and solved it by running:
"npm install assets-webpack-plugin --save-dev"

**Comment by ThulasiGuru** [comment]
Anyone can please share this the **Gentelella** in **angular 4** version.

**Comment by kmkatsma** [comment]
So this was inactive very long time, but I just updated to angular 7, and project is now based off of angular CLI.  So probably you've moved on, but just thought I should respond and close all the issues =)
