### ISSUE TITLE
webpack.validateSchema is not a function

### ISSUE THREAD

**Issue by PavelDanyliuk** [kmkatsma/angular2-webpack-starter-gentelella#2]
I just cloned repo, installed all the dependencies and use npm start.
os - Ubuntu 16.04

**Comment by crod93** [comment]
Try changing  "webpack-dev-server": "^2.1.0-beta.2", in package.json to "webpack-dev-server": "2.1.0-beta.2". Using npm install after.

**Comment by pihomeserver** [comment]
Solution confirmed

**Comment by kmkatsma** [comment]
So this was inactive very long time, but I just updated to angular 7, and project is now based off of angular CLI.  So probably you've moved on, but just thought I should respond and close all the issues =)
