### ISSUE TITLE
How to install this with Angular 4

### ISSUE THREAD

**Issue by mohinithorat** [kmkatsma/angular2-webpack-starter-gentelella#7]
How to install this with Angular 4

**Comment by portellapedro** [comment]
So do I.

**Comment by kmkatsma** [comment]
So this was inactive very long time, but I just updated to angular 7, and project is now based off of angular CLI.  So probably you've moved on, but just thought I should respond and close all the issues =)

**Comment by anderson361163** [comment]
Thank you @kmkatsma ^^
