### ISSUE TITLE
Module font-awesome 

### ISSUE THREAD

**Issue by joecutter** [kmkatsma/angular2-webpack-starter-gentelella#8]
Been trying to solve this issue but no success.
<img width="647" alt="screen shot 2019-02-08 at 12 09 12 pm" src="https://user-images.githubusercontent.com/11267062/52468877-05476100-2b9b-11e9-8dda-c25363012229.png">

**Comment by kmkatsma** [comment]
I just updated to angular 7, and project is now based off of angular CLI.  Try it now; this issue should be resolved.
